In [1]:
import pandas as pd
df=pd.read_excel('municipios.xlsx')
df.head(7)

,ANO,Código da Unidade da Federação,Nome da Unidade da Federação,Código do Município,Município,Esperança de vida ao nascer,Taxa de fecundidade total,Mortalidade infantil,Mortalidade até 5 anos de idade,Razão de dependência,...,População de 15 a 17 anos.1,População de 18 anos ou mais.1,População total em domicílios particulares permanentes,"População total em domicílios particulares permanentes, exceto com renda nula",Subíndice de escolaridade - IDHM Educação,Subíndice de frequência escolar - IDHM Educação,IDHM,IDHM Educação,IDHM Longevidade,IDHM Renda
0,2010,35,São Paulo,350010,ADAMANTINA,76.13,1.40,12.0,13.92,42.86,...,1563,26384,33490,33490,0.608,0.833,0.790,0.750,0.852,0.772
1,2010,35,São Paulo,350020,ADOLFO,75.62,1.81,13.8,15.98,42.22,...,152,2729,3557,3557,0.439,0.788,0.730,0.648,0.844,0.710
2,2010,35,São Paulo,350030,AGUAÍ,76.49,2.14,12.5,14.50,43.68,...,1681,23212,32089,32089,0.467,0.690,0.715,0.606,0.858,0.703
3,2010,35,São Paulo,350040,ÁGUAS DA PRATA,78.13,1.81,9.6,11.13,46.28,...,332,5886,7510,7510,0.554,0.814,0.781,0.716,0.886,0.750
4,2010,35,São Paulo,350050,ÁGUAS DE LINDÓIA,75.76,1.52,12.5,14.50,44.06,...,781,13053,17120,17120,0.510,0.776,0.745,0.675,0.846,0.725
5,2010,35,São Paulo,350055,ÁGUAS DE SANTA BÁRBARA,75.41,2.28,13.0,15.08,48.27,...,280,4038,5583,5570,0.555,0.778,0.757,0.695,0.840,0.744
6,2010,35,São Paulo,350060,ÁGUAS DE SÃO PEDRO,78.37,1.32,9.3,10.79,52.77,...,148,2113,2680,2680,0.751,0.864,0.854,0.825,0.890,0.849

In [2]:
list(df.columns)

['ANO',
 'Código da Unidade da Federação',
 'Nome da Unidade da Federação',
 'Código do Município',
 'Município',
 'Esperança de vida ao nascer',
 'Taxa de fecundidade total',
 'Mortalidade infantil',
 'Mortalidade até 5 anos de idade',
 'Razão de dependência',
 'Probabilidade de sobrevivência até 40 anos',
 'Probabilidade de sobrevivência até 60 anos',
 'Taxa de envelhecimento',
 'Expectativa de anos de estudo',
 'Taxa de analfabetismo - 11 a 14 anos',
 'Taxa de analfabetismo - 15 a 17 anos',
 'Taxa de analfabetismo - 15 anos ou mais',
 'Taxa de analfabetismo - 18 a 24 anos',
 'Taxa de analfabetismo - 18 anos ou mais',
 'Taxa de analfabetismo - 25 a 29 anos',
 'Taxa de analfabetismo - 25 anos ou mais',
 '% de 6 a 17 anos no básico sem atraso',
 '% de 6 a 14 anos no fundamental sem atraso',
 '% de 15 a 17 anos no médio sem atraso',
 '% de 6 a 17 no básico com 1 ano de atraso',
 '% de 6 a 14 anos no fundamental com 1 ano de atraso',
 '% de 15 a 17 no médio com 1 ano de atraso',
 '% de 6 a 17 anos no básico com 2 anos ou mais de atraso',
 '% de 6 a 14 anos no fundamental com 2 anos ou mais de atraso',
 '% de 15 a 17 anos no médio com 2 anos de atraso',
 'Taxa de frequência bruta ao básico',
 'Taxa de frequência bruta ao fundamental',
 'Taxa de frequência bruta ao médio',
 'Taxa de frequência bruta à pré-escola',
 'Taxa de frequência bruta ao superior',
 'Taxa de frequência líquida ao básico',
 'Taxa de frequência líquida ao fundamental',
 'Taxa de frequência líquida ao médio',
 'Taxa de frequência líquida à pré-escola',
 'Taxa de frequência líquida ao superior',
 '% de 0 a 3 anos na escola',
 '% de 11 a 14 anos na escola',
 '% de 15 a 17 anos na escola',
 '% de 18 a 24 anos na escola',
 '% de 25 a 29 anos na escola',
 '% de 4 a 5 anos na escola',
 '% de 4 a 6 anos na escola',
 '% de 5 a 6 anos na escola',
 '% de 6 anos na escola',
 '% de 6 a 14 anos na escola',
 '% de 6 a 17 anos na escola',
 '% de 15 a 17 anos no fundamental',
 '% de 18 a 24 anos no fundamental',
 '% de 4 a 5 anos no fundamental',
 '% de 18 a 24 anos no médio',
 '% de 6 a 14 anos no médio',
 '% de 15 a 17 anos no superior',
 '% de 11 a 13 anos nos anos finais do fundamental ou com fundamental completo',
 '% de 12 a 14 anos nos anos finais do fundamental ou com fundamental completo',
 '% de 15 a 17 anos com fundamental completo',
 '% de 16 a 18 anos com fundamental completo',
 '% de 18 a 24 anos com fundamental completo',
 '% de 18 anos ou mais com fundamental completo',
 '% de 25 anos ou mais com fundamental completo',
 '% de 18 a 20 anos com médio completo',
 '% de 18 a 24 anos com médio completo',
 '% de 18 anos ou mais com médio completo',
 '% de 19 a 21 anos com médio completo',
 '% de 25 anos ou mais com médio completo',
 '% de 25 anos ou mais com superior completo',
 'Renda per capita máxima do 1º quinto mais pobre',
 'Renda per capita máxima do 2° quinto mais pobre',
 'Renda per capita máxima do 3° quinto mais pobre',
 'Renda per capita máxima do 4°quinto mais pobre',
 'Renda per capita mínima do décimo mais rico',
 'Índice de Gini',
 '% de extremamente pobres',
 '% de crianças extremamente pobres',
 '% de pobres',
 '% de crianças pobres',
 '% de vulneráveis à pobreza',
 '% de crianças vulneráveis à pobreza',
 'Percentual da renda apropriada pelos 10% mais ricos',
 'Percentual da renda apropriada pelos 20% mais pobres',
 'Percentual da renda apropriada pelos 20% mais ricos',
 'Percentual da renda apropriada pelos 40% mais pobres',
 'Percentual da renda apropriada pelos 60% mais pobres',
 'Percentual da renda apropriada pelos 80% mais pobres',
 '% da renda proveniente de rendimentos do trabalho',
 'Razão 10% mais ricos / 40% mais pobres',
 'Razão 20% mais ricos / 40% mais pobres',
 'Renda per capita',
 'Renda per capita média do 1º quinto mais pobre',
 'Renda per capita média do décimo mais rico',
 'Renda per capita média do 2º quinto mais pobre',
 'Renda per capita média do 3º quinto mais pobre',
 'Renda per capita média do 4º quinto mais pobre',
 'Renda per capita média do quinto mais rico',
 'Renda per capita , exceto renda nula',
 'Renda per capita média dos extremamente pobres',
 'Renda per capita média dos pobres',
 'Renda per capita média dos vulneráveis à pobreza',
 'Índice de Theil - L',
 '% de trabalhadores por conta própria - 18 anos ou mais',
 '% de empregadores - 18 anos ou mais',
 '% dos ocupados no setor agropecuário - 18 anos ou mais',
 '% dos ocupados no setor comércio - 18 anos ou mais',
 '% dos ocupados no setor de construção - 18 anos ou mais',
 '% dos ocupados no setor extrativo mineral - 18 anos ou mais',
 'Grau de formalização dos ocupados - 18 anos ou mais',
 '% dos ocupados com fundamental completo - 18 anos ou mais',
 '% dos ocupados com médio completo - 18 anos ou mais',
 '% dos ocupados no setor serviços - 18 anos ou mais',
 '% dos ocupados no SIUP - 18 anos ou mais',
 '% dos ocupados com superior completo - 18 anos ou mais',
 '% dos ocupados na indústria de transformação - 18 anos ou mais',
 '% dos ocupados sem rendimento - 18 anos ou mais',
 '% dos ocupados com rendimento de até 1 s.m. - 18 anos ou mais',
 '% dos ocupados com rendimento de até 2 s.m. - 18 anos ou mais',
 '% dos ocupados com rendimento de até 3 s.m. - 18 anos ou mais',
 '% dos ocupados com rendimento de até 5 s.m. - 18 anos ou mais',
 'Rendimento médio dos ocupados - 18 anos ou mais',
 'Taxa de atividade - 10 anos ou mais',
 'Taxa de atividade - 10 a 14 anos',
 'Taxa de atividade - 15 a 17 anos',
 'Taxa de atividade - 18 a 24 anos',
 'Taxa de atividade - 18 anos ou mais',
 'Taxa de atividade - 25 a 29 anos',
 'Taxa de desocupação - 10 anos ou mais',
 'Taxa de desocupação - 10 a 14 anos',
 'Taxa de desocupação - 15 a 17 anos',
 'Taxa de desocupação - 18 a 24 anos',
 'Taxa de desocupação - 18 anos ou mais',
 'Taxa de desocupação - 25 a 29 anos',
 'Índice de Theil-L dos rendimentos do trabalho - 18 anos ou mais',
 '% de empregados com carteira - 18 anos ou mais',
 '% de trabalhadores do setor público - 18 anos ou mais',
 '% de empregados sem carteira - 18 anos ou mais',
 '% da população em domicílios com água encanada',
 '% da população em domicílios com banheiro e água encanada',
 '% da população em domicílios com densidade > 2',
 '% da população em domicílios com coleta de lixo',
 '% da população em domicílios com energia elétrica',
 '% de pessoas em domicílios com abastecimento de água e esgotamento sanitário inadequados',
 '% de pessoas em domicílios com paredes inadequadas',
 '% de crianças em domicílios em que ninguém tem fundamental completo',
 '% de crianças de 4 a 5 anos fora da escola',
 '% de crianças de 6 a 14 fora da escola',
 '% de pessoas em domicílios em que ninguém tem fundamental completo',
 '% de pessoas em domicílios vulneráveis à pobreza e em que ninguém tem fundamental completo.',
 '% de pessoas de 18 anos ou mais sem fundamental completo e em ocupação informal',
 '% de mulheres de 10 a 14 anos que tiveram filhos',
 '% de mulheres de 15 a 17 anos que tiveram filhos',
 '% de mães chefes de família sem fundamental completo e com filhos menores de 15 anos',
 '% de pessoas de 15 a 24 anos que não estudam nem trabalham e são vulneráveis à pobreza.',
 ' % de pessoas vulneráveis à pobreza e que gastam mais de uma hora até o trabalho',
 '% de pessoas em domicílios vulneráveis à pobreza e dependentes de idosos',
 '% de pessoas em domicílios sem energia elétrica',
 'População masculina de 0 a 4 anos',
 'População masculina de 10 a 14 anos',
 'População masculina de 15 a 19 anos',
 'População masculina de 20 a 24 anos',
 'População masculina de 25 a 29 anos',
 'População masculina de 30 a 34 anos',
 'População masculina de 35 a 39 anos',
 'População masculina de 40 a 44 anos',
 'População masculina de 45 a 49 anos',
 'População masculina de 50 a 54 anos',
 'População masculina de 55 a 59 anos',
 'População masculina de 5 a 9 anos',
 'População masculina de 60 a 64 anos',
 'População masculina de 65 a 69 anos',
 'População masculina de 70 a 74 anos',
 'População masculina de 75 a 79 anos',
 'População residente masculina',
 'População masculina com 80 anos e mais',
 'População feminina de 0 a 4 anos',
 'População feminina de 10 a 14 anos',
 'População feminina de 15 a 19 anos',
 'População feminina de 20 a 24 anos',
 'População feminina de 25 a 29 anos',
 'População feminina de 30 a 34 anos',
 'População feminina de 35 a 39 anos',
 'População feminina de 40 a 44 anos',
 'População feminina de 45 a 49 anos',
 'População feminina de 50 a 54 anos',
 'População feminina de 55 a 59 anos',
 'População feminina de 5 a 9 anos',
 'População feminina de 60 a 64 anos',
 'População feminina de 65 a 69 anos',
 'População feminina de 70 a 74 anos',
 'População feminina de 75 a 79 anos',
 'População feminina com 80 anos e mais',
 'População residente feminina',
 'PEA - 10 anos ou mais',
 'PEA - 10 a 14 anos',
 'PEA - 15 a 17 anos',
 'PEA - 18 anos ou mais',
 'População de até 1 ano',
 'População de 11 a 14 anos',
 'População de 11 a 13 anos',
 'População de 12 a 14 anos',
 'População de 1 a 3 anos',
 'População de 15 anos ou mais',
 'População de 15 a 17 anos',
 'População de 15 a 24 anos',
 'População de 16 a 18 anos',
 'População de 18 anos ou mais',
 'População de 18 a 20 anos',
 'População de 18 a 24 anos',
 'População de 19 a 21 anos',
 'População de 25 anos ou mais',
 'População de 4 anos',
 'População de 5 anos',
 'População de 6 anos',
 'População de 6 a 10 anos',
 'População de 6 a 17 anos',
 'População de 65 anos ou mais',
 'Mulheres de 10 a 14 anos',
 'Mulheres de 15 a 17 anos',
 'Mulheres de 15 anos ou mais',
 'Mulheres de 25 anos ou mais',
 'População rural',
 'População total',
 'População urbana',
 'População de 10 anos ou mais',
 'População de 10 a 14 anos',
 'População de 15 a 17 anos.1',
 'População de 18 anos ou mais.1',
 'População total em domicílios particulares permanentes',
 'População total em domicílios particulares permanentes, exceto com renda nula',
 'Subíndice de escolaridade - IDHM Educação',
 'Subíndice de frequência escolar - IDHM Educação',
 'IDHM',
 'IDHM Educação',
 'IDHM Longevidade',
 'IDHM Renda']

In [3]:
df.describe()

,ANO,Código da Unidade da Federação,Código do Município,Esperança de vida ao nascer,Taxa de fecundidade total,Mortalidade infantil,Mortalidade até 5 anos de idade,Razão de dependência,Probabilidade de sobrevivência até 40 anos,Probabilidade de sobrevivência até 60 anos,...,População de 15 a 17 anos.1,População de 18 anos ou mais.1,População total em domicílios particulares permanentes,"População total em domicílios particulares permanentes, exceto com renda nula",Subíndice de escolaridade - IDHM Educação,Subíndice de frequência escolar - IDHM Educação,IDHM,IDHM Educação,IDHM Longevidade,IDHM Renda
count,645.0,645.0,645.000000,645.000000,645.000000,645.000000,645.000000,645.000000,645.000000,645.000000,...,645.000000,6.450000e+02,6.450000e+02,6.450000e+02,645.000000,645.000000,645.000000,645.000000,645.000000,645.000000
mean,2010.0,35.0,352869.334884,75.153984,1.956884,14.448744,16.702481,44.841690,94.443116,83.485318,...,3084.548837,4.714444e+04,6.347923e+04,6.343470e+04,0.512434,0.780175,0.739527,0.676336,0.835992,0.716487
std,0.0,0.0,1670.029961,1.316245,0.329102,2.177029,2.517108,4.245718,0.701479,1.925024,...,20513.866624,3.393326e+05,4.511610e+05,4.509208e+05,0.079154,0.049662,0.032477,0.048391,0.021948,0.040270
min,2010.0,35.0,350010.000000,71.490000,1.250000,8.720000,10.110000,30.230000,92.270000,77.860000,...,42.000000,6.150000e+02,8.050000e+02,8.050000e+02,0.259000,0.632000,0.639000,0.520000,0.775000,0.592000
25%,2010.0,35.0,351460.000000,74.100000,1.720000,12.810000,14.850000,41.920000,93.910000,81.940000,...,265.000000,3.777000e+03,5.008000e+03,5.008000e+03,0.457000,0.748000,0.719000,0.644000,0.818000,0.691000
50%,2010.0,35.0,352870.000000,75.190000,1.940000,14.400000,16.640000,44.340000,94.420000,83.580000,...,633.000000,9.158000e+03,1.214400e+04,1.213800e+04,0.502000,0.776000,0.738000,0.678000,0.837000,0.716000
75%,2010.0,35.0,354320.000000,76.150000,2.180000,16.200000,18.700000,47.020000,95.010000,85.010000,...,1912.000000,2.788100e+04,3.733900e+04,3.733900e+04,0.566000,0.812000,0.761000,0.709000,0.853000,0.740000
max,2010.0,35.0,355730.000000,78.370000,2.880000,20.800000,24.010000,63.610000,96.120000,88.060000,...,506046.000000,8.410471e+06,1.117261e+07,1.116654e+07,0.762000,0.962000,0.862000,0.825000,0.890000,0.891000

In [4]:
dfn=df[df['Município']!='SÃO PAULO'].copy()#vou tirar Sampa

In [5]:
dfn.index=[i for i in range(644)]

In [6]:
mun=dfn['Município'].copy()

In [7]:
dfn=dfn.iloc[:,5:].copy()

In [8]:
dfn.head(6)

,Esperança de vida ao nascer,Taxa de fecundidade total,Mortalidade infantil,Mortalidade até 5 anos de idade,Razão de dependência,Probabilidade de sobrevivência até 40 anos,Probabilidade de sobrevivência até 60 anos,Taxa de envelhecimento,Expectativa de anos de estudo,Taxa de analfabetismo - 11 a 14 anos,...,População de 15 a 17 anos.1,População de 18 anos ou mais.1,População total em domicílios particulares permanentes,"População total em domicílios particulares permanentes, exceto com renda nula",Subíndice de escolaridade - IDHM Educação,Subíndice de frequência escolar - IDHM Educação,IDHM,IDHM Educação,IDHM Longevidade,IDHM Renda
0,76.13,1.40,12.0,13.92,42.86,94.72,85.06,12.61,10.39,0.96,...,1563,26384,33490,33490,0.608,0.833,0.790,0.750,0.852,0.772
1,75.62,1.81,13.8,15.98,42.22,94.76,84.20,10.57,10.13,0.00,...,152,2729,3557,3557,0.439,0.788,0.730,0.648,0.844,0.710
2,76.49,2.14,12.5,14.50,43.68,95.22,85.44,7.81,8.57,2.58,...,1681,23212,32089,32089,0.467,0.690,0.715,0.606,0.858,0.703
3,78.13,1.81,9.6,11.13,46.28,95.76,87.75,13.49,9.40,0.75,...,332,5886,7510,7510,0.554,0.814,0.781,0.716,0.886,0.750
4,75.76,1.52,12.5,14.50,44.06,94.51,84.54,10.77,9.92,1.24,...,781,13053,17120,17120,0.510,0.776,0.745,0.675,0.846,0.725
5,75.41,2.28,13.0,15.08,48.27,94.31,84.03,10.00,9.17,0.48,...,280,4038,5583,5570,0.555,0.778,0.757,0.695,0.840,0.744

In [9]:
import numpy as np

In [10]:
X=np.array(dfn)

In [15]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [16]:
scaler.fit(X)
XS=scaler.transform(X)

In [17]:
XS[:,190].mean(),XS[:,190].std()

(2.3445703625624425e-17, 1.0)

In [18]:
#fizemos com k=4 porque a própria cidade aparece como mais próxima a ela mesma...
from sklearn.neighbors import NearestNeighbors
nn=NearestNeighbors(n_neighbors=4)
nn.fit(XS)

NearestNeighbors(n_neighbors=4)

In [19]:
distances, indices = nn.kneighbors(XS)

Exercício 3<br/>
A idéia é localizar cidades com problemas de mortalidade infantil quando comparadas a cidades semelhantes a ela...

In [20]:
#os índices mostram as cidades mais semelhantes à primeira
#por exemplo, as cidades mais semelhantes à cidade 0 são 177,281 e 159
#se a cidade zero tiver maior mortalidade infantil que as cidades 177,281 e 159, deverá ser incluída na lista
#das cidades problemáticas
indices=np.array(indices)
indices[:5,:]

array([[  0, 177, 281, 159],
       [  1,  11, 158, 135],
       [  2, 356, 355, 592],
       [  3, 555, 473, 171],
       [  4, 562, 519, 260]])

In [21]:
#obtenha a lista das cidades com problema de Mortalidade infantil (mortalidade maior que a das 3 cidades mais semelhantes)

In [61]:
indices[:5,:]

array([[  0, 177, 281, 159],
       [  1,  11, 158, 135],
       [  2, 356, 355, 592],
       [  3, 555, 473, 171],
       [  4, 562, 519, 260]])

In [66]:
mI=dfn['Mortalidade infantil'].copy()
len(mI),len(mun)

(644, 644)

In [59]:
print(indices[2])

[  2 356 355 592]

In [84]:
count = 0
cidadesAltoIndice = []
for i in range(len(indices)):
    if mI[indices[i][0]] > (mI[indices[i][1]]) and mI[indices[i][0]] > (mI[indices[i][2]])\
    and mI[indices[i][0]] > (mI[indices[i][3]]):
        cidadesAltoIndice.append(mun[i])
        count+=1
print(count, len(cidadesAltoIndice))

147 147

In [75]:
print(cidadesAltoIndice)

['ÁGUAS DE SANTA BÁRBARA', 'ALAMBARI', 'ALTAIR', 'ALTO ALEGRE', 'ÁLVARES FLORENCE', 'ÁLVARO DE CARVALHO', 'ALVINLÂNDIA', "APARECIDA D'OESTE", 'ARAÇATUBA', 'ARANDU', 'ARCO-ÍRIS', 'AREIAS', 'ARIRANHA', 'ARTUR NOGUEIRA', 'BADY BASSITT', 'BALBINOS', 'BARRA DO CHAPÉU', 'BARRA DO TURVO', 'BERTIOGA', 'BOFETE', 'BOM JESUS DOS PERDÕES', 'BOM SUCESSO DE ITARARÉ', 'BRODOWSKI', 'BROTAS', 'BURI', 'BURITIZAL', 'CAÇAPAVA', 'CAJOBI', 'CANITAR', 'CARAPICUÍBA', 'CESÁRIO LANGE', 'COROADOS', 'CRISTAIS PAULISTA', 'DOBRADA', 'DOURADO', 'DUARTINA', 'ELIAS FAUSTO', 'EMILIANÓPOLIS', 'ESPÍRITO SANTO DO TURVO', 'EUCLIDES DA CUNHA PAULISTA', 'FERNANDÓPOLIS', 'FERRAZ DE VASCONCELOS', 'FLORA RICA', 'FLÓRIDA PAULISTA', 'FRANCISCO MORATO', 'GABRIEL MONTEIRO', 'GASTÃO VIDIGAL', 'GAVIÃO PEIXOTO', 'GENERAL SALGADO', 'GUARAÇAÍ', "GUARANI D'OESTE", 'GUAREÍ', 'GUZOLÂNDIA', 'IBATÉ', 'ICÉM', 'IGARAPAVA', 'INDIAPORÃ', 'ITANHAÉM', 'ITAQUAQUECETUBA', 'ITATIBA', 'ITIRAPINA', 'ITOBI', 'ITU', 'JABOTICABAL', 'JANDIRA', 'JERIQUARA', 'JOÃO RAMALHO', 'JUQUITIBA', 'LAGOINHA', 'LIMEIRA', 'LORENA', 'LUCIANÓPOLIS', 'MARTINÓPOLIS', 'MIRACATU', 'MIRA ESTRELA', 'MOCOCA', 'MONÇÕES', 'NANTES', 'NEVES PAULISTA', 'NOVA CANAÃ PAULISTA', 'NOVA GRANADA', 'NUPORANGA', 'OSVALDO CRUZ', 'OURO VERDE', 'PARAGUAÇU PAULISTA', 'PAULICÉIA', 'PAULÍNIA', 'PAULO DE FARIA', 'PEDERNEIRAS', 'PEDRA BELA', 'PILAR DO SUL', 'PINDAMONHANGABA', 'PIQUETE', 'PIRACICABA', 'PIRATININGA', 'PONTES GESTAL', 'PORTO FERREIRA', 'POTIM', 'PRAIA GRANDE', 'PRATÂNIA', 'QUELUZ', 'RIBEIRA', 'RIBEIRÃO BONITO', 'RIBEIRÃO BRANCO', 'RIBEIRÃO PRETO', 'RIFAINA', 'RIO CLARO', 'RIO GRANDE DA SERRA', 'ROSANA', 'ROSEIRA', 'SABINO', 'SALTINHO', 'SANTA ALBERTINA', 'SANTA BRANCA', "SANTA CLARA D'OESTE", 'SANTA CRUZ DAS PALMEIRAS', 'SANTA ERNESTINA', 'SANTA FÉ DO SUL', 'SANTA LÚCIA', 'SANTA MARIA DA SERRA', 'SANTANA DE PARNAÍBA', 'SANTO ANTÔNIO DO ARACANGUÁ', 'SANTOS', 'SÃO JOÃO DAS DUAS PONTES', 'SÃO MANUEL', 'SÃO SEBASTIÃO DA GRAMA', 'SARUTAIÁ', 'SERRA AZUL', 'SERTÃOZINHO', 'SEVERÍNIA', 'SUD MENNUCCI', 'TABATINGA', 'TAMBAÚ', 'TAQUARITINGA', 'TAQUARITUBA', 'TATUÍ', 'TUPÃ', 'TUPI PAULISTA', 'UBATUBA', 'UBIRAJARA', 'URÂNIA', 'URUPÊS', 'VALENTIM GENTIL', 'VALINHOS', 'VERA CRUZ', 'VITÓRIA BRASIL', 'VOTORANTIM']